apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
  labels:
    app: {{ .Values.db.service.name }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
  - name: {{ .Values.db.service.name }}
    protocol: TCP
    port: {{ .Values.db.service.port }}
    targetPort: {{ .Values.db.service.targetPort }}
  selector:
    app: {{ .Values.db.name }}
